// Code generated by mockery v2.40.1. DO NOT EDIT.

package mocks

import (
	git "github.com/go-git/go-git/v5"

	mock "github.com/stretchr/testify/mock"
)

// Object is an autogenerated mock type for the Object type
type Object struct {
	mock.Mock
}

// Open provides a mock function with given fields: path
func (_m *Object) Open(path string) (*git.Repository, error) {
	ret := _m.Called(path)

	if len(ret) == 0 {
		panic("no return value specified for Open")
	}

	var r0 *git.Repository
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*git.Repository, error)); ok {
		return rf(path)
	}
	if rf, ok := ret.Get(0).(func(string) *git.Repository); ok {
		r0 = rf(path)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*git.Repository)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(path)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewObject creates a new instance of Object. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewObject(t interface {
	mock.TestingT
	Cleanup(func())
}) *Object {
	mock := &Object{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
