version: 2024-02-04
release:
  version: 1.0.0
config:
  default:
    version: 0.0.0
  modes:
    flex:
      trigger:
        major: "[bump major]"
        minor: "[bump minor]"
        patch: "[bump patch]"
        auto: "[bump auto]"
    auto:
      trigger:
        major: "BREAKING CHANGE:"
        minor: "feat:"
        patch: "fix:"
  vcs:
    messages:
      commit: "Bump Version [%s] -> [%s]"
      tag: "Tagged by gitver"
    format:
      versionTag: "v%s"
  files:
    - filepath: ./test/pom.xml
      format: xml
      xpath: /root/version
    - filepath: ./test/test.json
      format: json
      jsonpath:
    - filepath: ./test/test.txt
      format: text
      placeholder: {VERSION}
